### ISSUE TITLE
Evolution: make AsciidocFX pluggable

### ISSUE THREAD

**Issue by Ayowel** [asciidocfx/AsciidocFX#519]
This is a tracking issue for the evolution as I'm going to split it in several issues

__Goals :__

* Normalize & document interfaces
* Lower coupling between services
* Permit dynamic components loading

Target steps:

* [X] Move services to dedicated implementation folders - #518
* [X] Create services interfaces and have implementations extend them - #518
* [ ] Ongoing: Create a Service Loader & update contructors (Related to #272)
* [ ] Cleanup parameters & fix typos in interfaces functions (`setWorkigDirectory`...)
* [ ] Lower internal models exposition in services interfaces (mostly : avoid JavaFX-specific/GUI object types in non-ui services functions), Create/update UI functions to handle those functionnalities
* [ ] Add dynamic class loading to add build features (POC)
* [ ] Add dynamic class loading to add build features - document interfaces
* [ ] Add loaded classes configuration support in settings
* [ ] Add injection points for plugins in UI
* [ ] Add dynamic loading support for live enable/disable ?
* [ ] Other stuff ?

My end goal, which would be addressed in further PRs after this, is to be able to run AsciidocFX to build PDF/HTML/... with AsciidocFX on a server without GUI so that high-level users can rely on the output they see to be reproduced on a CI platform.

**Comment by Ayowel** [comment]
Quick heads-up. I'm still looking into ways to properly handle dynamic resources loading and though I wanted to avoid it, I think I'll have to use OSGi to get a satisfactory solution, however that implies huge refactoring & splitting the codebase in several projects. 

I probably won't have the time for such an undertaking before October.

Note that by the end of these modifications, products should be uploaded to maven/ant/... repositories so that developers can specify them as dependencies.
